name: cflutter
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  cupertino_icons:
  equatable:
  flutter:
    sdk: flutter
  flutter_spinkit:
  http:
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
