name: cflutter
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  cupertino_icons: 1.0.0
  equatable: 1.2.5
  flutter:
    sdk: flutter
  flutter_spinkit: 4.1.2+1
  http: 0.12.2
  provider: 4.3.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
